<IMG SRC="http://users.rsise.anu.edu.au/~baumgart/Peter-Baumgartner.jpg" height=230 align="right" border=0 alt="Peter Baumgartner in 2003"></a> 
<h2>Peter Baumgartner</h2>

   Principal Researcher, <A HREF="http://www.nicta.com.au/">NICTA</a> 
<br>
Research Group Manager/Managing Complexity<br>
   and <A HREF="http://www.anu.edu.au/">ANU</a> Adjunct Member
<br>
<br>

<A HREF="http://users.rsise.anu.edu.au/~baumgart/contact.html">Details and Contact</a>
<br>
<hr>


